"""empty message

Revision ID: 787da9ff0555
Revises: ef7e7e7b9d1b
Create Date: 2021-06-19 20:06:57.129529

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '787da9ff0555'
down_revision = 'ef7e7e7b9d1b'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_documents',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'event_id', name='uq_ed_name_event')
    )
    op.add_column('events', sa.Column('is_document_enabled', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('events_version', sa.Column('is_document_enabled', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'is_document_enabled')
    op.drop_column('events', 'is_document_enabled')
    op.drop_table('event_documents')
    # ### end Alembic commands ###
